name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y \
          gcc-aarch64-linux-gnu \
          binutils-aarch64-linux-gnu \
          bc bison flex \
          libssl-dev libelf-dev \
          clang lld

    - name: Configure
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        make exynos9830-z3sxxx_defconfig

    - name: Build
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        make -j$(nproc)

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: kernel
        path: |
          arch/arm64/boot/Image*
          arch/arm64/boot/dts/**/*.dtb
